name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    types: [opened, reopened, synchronize]
  schedule:
    - cron: '0 0 * * 0'  # weekly sundays at midnight

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        rust: [stable, nightly]
    steps:
      - name: Setup rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          override: true
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --verbose

  no-default-feature-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        rust: [stable, nightly]
        feature: [fnv-hash, sip-hash]
    steps:
      - name: Setup rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          override: true
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --verbose --no-default-features --features ${{ matrix.feature }},uuid-extras

  clippy:
    name: cargo clippy
    runs-on: ubuntu-latest
    steps:
      - name: Install nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly-2023-02-11
          override: true
          components: rustfmt, clippy
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Run cargo clippy (default)
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all-targets -- -D warnings
      - name: Run cargo clippy (fnv)
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all-targets --no-default-features --features fnv-hash,uuid-extras -- -D warnings
      - name: Run cargo clippy (sip)
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all-targets --no-default-features --features sip-hash,uuid-extras -- -D warnings

  format:
    name: cargo fmt
    runs-on: ubuntu-latest
    steps:
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly-2023-02-11
          override: true
          components: rustfmt, clippy
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Run cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
